#!/usr/bin/env bash

set -e

# if [ "$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')" != "staging" ]
# then
#   echo "Must be on staging branch to deploy to staging"
#   exit 1
# fi

npm run build

S3_BUCKET="s3://enriquechong-static-html"

aws s3 sync --delete build/ $S3_BUCKET
aws cloudfront create-invalidation --distribution-id EYA7ZCGHBVFFH --paths "/*"
